#!/bin/bash -eu
# Create an encrypted backup (in 5 GB pieces) inside our scratch space.
#
# This can be put on a hard drive and stored under the SM's mattress, uploaded
# to Google Nearline, automatically uploaded to Box.com, etc.
set -o pipefail

ARCHIVE_DIRECTORY="/opt/backups/scratch/archive"
SNAPSHOT_PATH="/opt/backups/live/rsnapshot"

# import staff keys into temporary gpg dir
gpgdir=$(mktemp -d)
gpg --homedir "$gpgdir" --quiet --import /opt/share/backups/keys/*.asc

umask 077
rm -rf "$ARCHIVE_DIRECTORY"
mkdir "$ARCHIVE_DIRECTORY"

compress_and_encrypt() {
    tar -I pigz -cf - $SNAPSHOT_PATH |
        gpg --homedir "$gpgdir" \
            --quiet \
            --encrypt \
            --trust-model always \
            --compress-algo none \
            --recipient porrliam@gmail.com
}

split_parts() {
    split -d -a 4 -b 5G - \
        "${ARCHIVE_DIRECTORY}/backup-$(date +%Y-%m-%d).img.gz.gpg.part"
}

# Only show pv output if the terminal is interactive (no cron email pv spam)
if [ -t 0 ]; then
    compress_and_encrypt | pv | split_parts
else
    compress_and_encrypt | split_parts
fi
